name: Despliegue automático con Surge.sh

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  

      - name: Instalar Surge.sh globalmente
        run: npm install -g surge

      - name: Desplegar con Surge.sh
        run: surge ./ --domain P1web.surge.sh  
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}  
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  